### ISSUE TITLE
this is a shit

### ISSUE THREAD

**Issue by RookieCuzz** [DeeChael/visual-api#1]
shit

**Comment by DeeChael** [comment]
u r totally like ur name: rookie
saying a open-source project a shit and not point out the problem.
this project is just for myself and i just put it on github, then it is not continued for a long period. i don't know what's wrong with u

**Comment by DeeChael** [comment]
checked
almost all of ur projects is forked
when u can start a project and continuously develop it then criticize others otherwise u all totally shit urself

**Comment by RookieCuzz** [comment]
A powerful camera？也好意思这样说powerful, 写了一堆x山.
VisualBukkitPlugin类的静态属性ANIMATION_MANAGER最后调用到了VisualBukkitPlugin自己的实例对象和未初始化的静态属性,你这代码能跑起来也是逆天.
开源不代表你能把自己的屎乱拉,还骗别人这个能吃.

**Comment by DeeChael** [comment]
只会乱喷，那你自己写啊？
我又没让你用
你这么牛逼你怎么没写几个项目全是 fork 呢？
把我所有的项目全评价一遍 shit 啊？
中国开源环境就是被你这种喜欢乱评价的人破坏的

**Comment by DeeChael** [comment]
你觉得屎山那你提出解决方案
谁提出谁解决，这是开发中唯一的真理
只会输出自己的情绪只能展现出你自己的无能

**Comment by RookieCuzz** [comment]
你是不知道什么叫私人仓库？
还是那句话开源不代表你能把自己的屎乱拉,还骗别人这个能吃,纯纯浪费别人的时间.
而且我也只是阐述事实,提醒后面的人这代码有问题,我的建议是javaSe再去学学.

**Comment by RookieCuzz** [comment]
不是IDE不报错你的代码就没问题

**Comment by nostalfinals** [comment]
**您是现实生活过的很不如意吗？**
真是奇怪。我寻思该仓库的所有者也没招你惹你吧？如果您觉得配不上 "powerful" 一词，可以提出哪里不好，哪里还有改进空间，而不是一上来就说一句这是屎。

**Comment by RookieCuzz** [comment]
这不是屎是什么？难道还要夸写得好吗,大家多来看看这项目。

**Comment by nostalfinals** [comment]
阁下是有什么很吊炸天，很出名的项目吗？
我其实没有想明白，这个仓库也没有很多 star 吧。您是怎么看见这个仓库，然后再进来喷一句的？
您的仓库列表里我暂时还没有发现什么原创的，值得研究的项目。
我请您与他人交谈时放尊重一点，不要在 GitHub 上败坏中国人的名声。

**Comment by DeeChael** [comment]
40 个 fork
两个自己的项目
一个 java 的跟爱发电有关，看来是你圈钱的
还有一个 python 的


你评价可以，那你把所有问题写出来并给出解决方案
我说了你这样就是输出情绪
破坏中国的开源环境
我为什么要开私人仓库
这是我的代码又不是你的，你管得着吗
我这又不是一个公开的项目
我这里面也给出一部分 bukkit 相关的代码代码可以用来学习参考

**Comment by RookieCuzz** [comment]
那我这边给您诚挚道个歉,是我个人问题,您的项目代码没有任何问题. 不过还是建议你再去学下JAVASE.

**Comment by DeeChael** [comment]
你好厉害啊，竟然学了 javase，不像我，只是一个开发爱好者，大学学的建筑学，希望你能住上我设计的房子呢，我一定好好给你把承重墙的位置设计的稳稳当当的

**Comment by zimzaza4** [comment]
不是哥们 这就是个几个star都不到的小项目 你也巴不得来这踩一脚 那github 这么多屎项目你是不是要一个一个挨着骂一遍

**Comment by postyizhan** [comment]
围观，看看乐子

**Comment by EroslonDusk** [comment]
人类群星闪耀时刻

**Comment by nostalwillbefine** [comment]
阁下怎么还把我拉黑了？
我好像没有说任何脏字，仅仅是反驳您的观点就要拉黑我吗？
噢不对，我好像没有在您的 Issue 下看见任何有价值的观点，只看见了别人走在路上被您莫名其妙的输出了一顿情绪。

**Comment by wangjia184** [comment]
是因为在现实生活中过得不如意？所以才会跑到最大的同性交友平台上发泄么？ @RookieCuzz
